/*
 * CS106L Assignment 2: Marriage Pact
 * Created by Haven Whitney with modifications by Fabio Ibanez & Jacob Roberts-Baca.
 *
 * Welcome to Assignment 2 of CS106L! Please complete each STUDENT TODO
 * in this file. You do not need to modify any other files.
 *
 */

#include <fstream>
#include <iostream>
#include <queue>
#include <set>
#include <string>
#include <unordered_set>
#include <cstdlib>  // 用于 std::rand(), std::srand()
#include <ctime>
#include <sstream>

std::string kYourName = "Dylan Tai"; // Don't forget to change this!

/**
 * Takes in a file name and returns a set containing all of the applicant names as a set.
 *
 * @param filename  The name of the file to read.
 *                  Each line of the file will be a single applicant's name.
 * @returns         A set of all applicant names read from the file.
 *
 * @remark Feel free to change the return type of this function (and the function
 * below it) to use a `std::unordered_set` instead. If you do so, make sure
 * to also change the corresponding functions in `utils.h`.
 */
std::set<std::string> get_applicants(std::string filename) {

  std::ifstream ifs(filename);
  std::string line;

  std::set<std::string> students;

  while (std::getline (ifs, line)){

    students.insert(line);

  }
  
  ifs.close();
  return students;

}

/**
 * Takes in a set of student names by reference and returns a queue of names
 * that match the given student name.
 *
 * @param name      The returned queue of names should have the same initials as this name.
 * @param students  The set of student names.
 * @return          A queue containing pointers to each matching name.
 */
std::queue<const std::string*> find_matches(std::string name, const std::set<std::string>& students) {
  


  std::queue<const std::string*> candidates;

  std::string first, last;
  std::stringstream ss(name);
  ss >> first >> last;
  char i = first[0];
  char j = last[0];

  for (auto it = students.begin(); it != students.end(); ++it){

    std::stringstream nn (*it);
    std::string fn, sn;
    nn >> fn >> sn;

    if ( fn[0] == i ){


      if ( sn[0] == j ){

        candidates.push (&(*it));

      }

    }

  }

  return candidates;

}





/**
 * Takes in a queue of pointers to possible matches and determines the one true match!
 *
 * You can implement this function however you'd like, but try to do something a bit
 * more complicated than a simple `pop()`.
 *
 * @param matches The queue of possible matches.
 * @return        Your magical one true love.
 *                Will return "NO MATCHES FOUND." if `matches` is empty.
 */
std::string get_match(std::queue<const std::string*>& matches) {
  // STUDENT TODO: Implement this function.

  if ( matches.empty() ){

    return "NO MATCHES FOUND.";

  }

  //random function is generated by AI cuz I have totally forgotten it TT
  std::srand(std::time(0));
  int random_index = std::rand() % matches.size();//随机选一个

  for (int i = 0; i < random_index; i++) {
        matches.pop();
    }//走到随机位置

  std::string match = *matches.front();//取第一个（但已经是第 random_index+1 个了）

  return match;

}

/* #### Please don't remove this line! #### */
#include "autograder/utils.hpp"
